<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Invoice Types
        $invoiceTypes = [
            ['01', 'Standard Invoice'],
            ['02', 'Debit Note'],
            ['03', 'Credit Note'],
            ['04', 'Self-Billed Invoice'],
            ['05', 'Self-Billed Debit Note'],
            ['06', 'Self-Billed Credit Note'],
            ['07', 'Consolidated Invoice'],
            ['08', 'Consolidated Debit Note'],
            ['09', 'Consolidated Credit Note'],
            ['10', 'Self-Billed Consolidated Invoice'],
            ['11', 'Self-Billed Consolidated Debit Note'],
            ['12', 'Self-Billed Consolidated Credit Note'],
        ];

        foreach ($invoiceTypes as $type) {
            Setting::firstOrCreate(
                [
                    'category' => 'InvoiceType',
                    'name' => $type[0],
                ],
                [
                    'value' => $type[1],
                    'description' => $type[1],
                    'is_active' => true,
                ]
            );
        }

        // Malaysian States
        $states = [
            ['14', 'Wilayah Persekutuan Kuala Lumpur'],
            ['10', 'Wilayah Persekutuan Putrajaya'],
            ['15', 'Wilayah Persekutuan Labuan'],
            ['01', 'Johor'],
            ['02', 'Kedah'],
            ['03', 'Kelantan'],
            ['04', 'Melaka'],
            ['05', 'Negeri Sembilan'],
            ['06', 'Pahang'],
            ['07', 'Pulau Pinang'],
            ['08', 'Perak'],
            ['09', 'Perlis'],
            ['11', 'Selangor'],
            ['12', 'Terengganu'],
            ['13', 'Sabah'],
            ['16', 'Sarawak'],
        ];

        foreach ($states as $state) {
            Setting::firstOrCreate(
                [
                    'category' => 'State',
                    'name' => $state[0],
                ],
                [
                    'value' => $state[1],
                    'description' => $state[1],
                    'is_active' => true,
                ]
            );
        }

        // Common Countries (ISO 3166-1 alpha-2)
        $countries = [
            ['MY', 'Malaysia'],
            ['SG', 'Singapore'],
            ['ID', 'Indonesia'],
            ['TH', 'Thailand'],
            ['PH', 'Philippines'],
            ['VN', 'Vietnam'],
            ['CN', 'China'],
            ['JP', 'Japan'],
            ['KR', 'South Korea'],
            ['TW', 'Taiwan'],
            ['IN', 'India'],
            ['GB', 'United Kingdom'],
            ['US', 'United States'],
            ['AU', 'Australia'],
            ['NZ', 'New Zealand'],
            ['AE', 'United Arab Emirates'],
            ['SA', 'Saudi Arabia'],
        ];

        foreach ($countries as $country) {
            Setting::firstOrCreate(
                [
                    'category' => 'Country',
                    'name' => $country[0],
                ],
                [
                    'value' => $country[1],
                    'description' => $country[1],
                    'is_active' => true,
                ]
            );
        }

        // Common MSIC Codes (Malaysia Standard Industrial Classification)
        $msicCodes = [
            ['01111', 'Growing of cereals (except rice), legumes and oil seeds'],
            ['01210', 'Growing of rice'],
            ['01410', 'Growing of vegetables'],
            ['01511', 'Planting of oil palm'],
            ['02200', 'Forestry and logging'],
            ['03110', 'Marine fishing'],
            ['05110', 'Mining of iron ores'],
            ['06100', 'Extraction of crude petroleum and natural gas'],
            ['07101', 'Mining of gold ores'],
            ['08101', 'Quarrying of stone, sand and clay'],
            ['09100', 'Support activities for petroleum and natural gas mining'],
            ['10100', 'Processing and preserving of meat'],
            ['10200', 'Processing and preserving of fish, crustaceans and molluscs'],
            ['10300', 'Processing and preserving of fruits and vegetables'],
            ['10410', 'Manufacture of vegetable oils and fats'],
            ['10500', 'Manufacture of dairy products'],
            ['10610', 'Grain milling'],
            ['10620', 'Starches and starch products'],
            ['10710', 'Bakery products'],
            ['10720', 'Sugar confectionery'],
            ['10800', 'Manufacture of other food products'],
            ['11010', 'Distilling, rectifying and blending of spirits'],
            ['11020', 'Manufacture of wine'],
            ['11030', 'Manufacture of malt liquors and malt'],
            ['12000', 'Manufacture of tobacco products'],
            ['13100', 'Preparation and spinning of textile fibres'],
            ['13910', 'Manufacture of knitted and crocheted fabrics'],
            ['13921', 'Manufacture of woven fabrics'],
            ['14100', 'Manufacture of wearing apparel, except fur apparel'],
            ['14301', 'Tanning and dressing of leather'],
            ['15101', 'Leather tanning'],
            ['16210', 'Manufacture of veneer sheets and wood-based panels'],
            ['16220', 'Manufacture of parquet flooring'],
            ['16230', 'Manufacture of other builders\' carpentry and joinery'],
            ['17010', 'Manufacture of pulp'],
            ['17020', 'Manufacture of paper and paperboard'],
            ['18101', 'Printing of newspapers'],
            ['18102', 'Other printing'],
            ['19100', 'Manufacture of coke oven products'],
            ['19210', 'Manufacture of refined petroleum products'],
            ['20100', 'Manufacture of basic chemicals'],
            ['20210', 'Manufacture of fertilizers and pesticides'],
            ['20220', 'Manufacture of plastics in primary forms'],
            ['20900', 'Manufacture of other chemical products'],
            ['21010', 'Manufacture of pharmaceuticals'],
            ['22110', 'Manufacture of rubber tyres and tubes'],
            ['22120', 'Retreading and rebuilding of rubber tyres'],
            ['22190', 'Manufacture of other rubber products'],
            ['22210', 'Manufacture of plastic plates, sheets and tubes'],
            ['22290', 'Manufacture of other plastic products'],
            ['23910', 'Production of glass and glass products'],
            ['23991', 'Manufacture of ceramic household and ornamental articles'],
            ['23992', 'Manufacture of ceramic sanitary fixtures'],
            ['23993', 'Manufacture of ceramic refractory products'],
            ['24100', 'Manufacture of basic iron and steel'],
            ['24200', 'Manufacture of basic precious and non-ferrous metals'],
            ['24310', 'Casting of iron'],
            ['24320', 'Casting of steel'],
            ['25110', 'Manufacture of metal structures and parts of structures'],
            ['25120', 'Manufacture of metal doors and windows'],
            ['25910', 'Manufacture of cutlery'],
            ['25920', 'Manufacture of locks and hinges'],
            ['25930', 'Manufacture of metal wire and wire products'],
            ['26100', 'Manufacture of electronic components and boards'],
            ['26201', 'Manufacture of television receivers'],
            ['26202', 'Manufacture of sound and video equipment'],
            ['26301', 'Manufacture of computers'],
            ['26302', 'Manufacture of computer peripherals'],
            ['26400', 'Manufacture of consumer electronics'],
            ['26800', 'Manufacture of magnetic and optical media'],
            ['27100', 'Manufacture of electric motors, generators and transformers'],
            ['27200', 'Manufacture of electricity distribution and control apparatus'],
            ['27300', 'Manufacture of insulated wire and cable'],
            ['27400', 'Manufacture of electric accumulators and batteries'],
            ['27500', 'Manufacture of electric lighting equipment'],
            ['28110', 'Manufacture of engines and turbines'],
            ['28120', 'Manufacture of fluid power equipment'],
            ['28130', 'Manufacture of pumps and compressors'],
            ['28910', 'Manufacture of machinery for metallurgy'],
            ['28920', 'Manufacture of machinery for mining, quarrying and construction'],
            ['28930', 'Manufacture of machinery for food and beverage processing'],
            ['28990', 'Manufacture of other special-purpose machinery'],
            ['29101', 'Manufacture of motor vehicles'],
            ['29201', 'Manufacture of vehicle bodies'],
            ['29202', 'Manufacture of trailers and semi-trailers'],
            ['29300', 'Manufacture of parts and accessories for motor vehicles'],
            ['30100', 'Building of ships and floating structures'],
            ['30300', 'Manufacture of air and spacecraft and related machinery'],
            ['30910', 'Manufacture of motorcycles'],
            ['30920', 'Manufacture of bicycles'],
            ['31000', 'Manufacture of furniture'],
            ['32100', 'Manufacture of jewellery and related articles'],
            ['32200', 'Manufacture of musical instruments'],
            ['32300', 'Manufacture of sports goods'],
            ['32400', 'Manufacture of games and toys'],
            ['33110', 'Repair of fabricated metal products'],
            ['33120', 'Repair of machinery'],
            ['33130', 'Repair of electronic and optical equipment'],
            ['33140', 'Repair of transport equipment'],
            ['33190', 'Repair of other equipment'],
            ['35110', 'Electric power generation'],
            ['35120', 'Electric power transmission and distribution'],
            ['35200', 'Manufacture and distribution of gas'],
            ['35300', 'Steam and air conditioning supply'],
            ['36000', 'Water collection, treatment and supply'],
            ['37000', 'Sewerage'],
            ['38110', 'Collection of non-hazardous waste'],
            ['38120', 'Collection of hazardous waste'],
            ['41010', 'Construction of residential buildings'],
            ['41020', 'Construction of non-residential buildings'],
            ['42101', 'Construction of highways'],
            ['42102', 'Construction of streets'],
            ['42103', 'Construction of bridges and tunnels'],
            ['42200', 'Construction of utility projects'],
            ['42910', 'Surface coating and roads'],
            ['42990', 'Other construction'],
            ['45101', 'Sale of motor vehicles'],
            ['45102', 'Sale of motorcycles'],
            ['45200', 'Maintenance and repair of motor vehicles'],
            ['45300', 'Sale of motor vehicle parts and accessories'],
            ['45401', 'Sale of fuel'],
            ['46101', 'Wholesale on a fee or contract basis'],
            ['46102', 'Wholesale of agricultural raw materials and live animals'],
            ['46103', 'Wholesale of food, beverages and tobacco'],
            ['46104', 'Wholesale of household goods'],
            ['46105', 'Wholesale of machinery and equipment'],
            ['46106', 'Wholesale of other goods'],
            ['47101', 'Retail sale in non-specialized stores'],
            ['47102', 'Retail sale of food in specialized stores'],
            ['47103', 'Retail sale of automotive fuel in specialized stores'],
            ['47210', 'Retail sale of textiles in specialized stores'],
            ['47220', 'Retail sale of hardware and paints'],
            ['47300', 'Retail sale of automotive fuel'],
            ['47410', 'Retail sale of computers'],
            ['47420', 'Retail sale of telecommunications equipment'],
            ['47430', 'Retail sale of audio and video equipment'],
            ['47440', 'Retail sale of other household equipment'],
            ['47510', 'Retail sale of textiles'],
            ['47520', 'Retail sale of hardware and paints'],
            ['47530', 'Retail sale of carpets and rugs'],
            ['47590', 'Retail sale of other goods'],
            ['47610', 'Retail sale of books'],
            ['47620', 'Retail sale of newspapers and magazines'],
            ['47630', 'Retail sale of music and video recordings'],
            ['47710', 'Retail sale of footwear'],
            ['47720', 'Retail sale of clothing and accessories'],
            ['47730', 'Retail sale of pharmaceutical and medical goods'],
            ['47740', 'Retail sale of cosmetics and toiletries'],
            ['47750', 'Retail sale of flowers and plants'],
            ['47760', 'Retail sale of second-hand goods'],
            ['47770', 'Retail sale of food in specialized stores'],
            ['47780', 'Retail sale of other goods'],
            ['49100', 'Transport via railways'],
            ['49210', 'Urban and suburban passenger land transport'],
            ['49220', 'Other passenger land transport'],
            ['49230', 'Freight rail transport'],
            ['49300', 'Transport via pipelines'],
            ['50101', 'Sea and coastal passenger water transport'],
            ['50102', 'Sea and coastal freight water transport'],
            ['50200', 'Inland passenger water transport'],
            ['50300', 'Inland freight water transport'],
            ['50400', 'Transport via waterways'],
            ['51101', 'Passenger air transport'],
            ['51102', 'Freight air transport'],
            ['51210', 'Air space control'],
            ['51220', 'Airport activities'],
            ['52100', 'Warehousing and storage'],
            ['52210', 'Service activities incidental to land transportation'],
            ['52220', 'Service activities incidental to water transportation'],
            ['52230', 'Service activities incidental to air transportation'],
            ['52240', 'Cargo handling'],
            ['53100', 'Postal activities'],
            ['53201', 'Courier activities'],
            ['53202', 'Door-to-door messenger activities'],
            ['55101', 'Hotels'],
            ['55102', 'Motels'],
            ['55103', 'Resorts'],
            ['55201', 'Holiday homes'],
            ['55202', 'Short-term accommodation'],
            ['56101', 'Restaurants and mobile food service activities'],
            ['56102', 'Event catering'],
            ['56210', 'Event catering'],
            ['56290', 'Other food service activities'],
            ['58110', 'Book publishing'],
            ['58120', 'Directories and mailing lists publishing'],
            ['58130', 'Software publishing'],
            ['58190', 'Other publishing'],
            ['59110', 'Motion picture and video production'],
            ['59120', 'Motion picture and video distribution'],
            ['59130', 'Motion picture projection'],
            ['59200', 'Video tape and disc rental'],
            ['60100', 'Radio broadcasting'],
            ['60200', 'Television programming and broadcasting'],
            ['61100', 'Telecommunications'],
            ['61200', 'Television programming'],
            ['61300', 'Computer programming'],
            ['61900', 'Other information technology and computer service activities'],
            ['62010', 'Data processing'],
            ['62020', 'Web portals'],
            ['62030', 'Data hosting'],
            ['63110', 'Data processing'],
            ['63120', 'Web portals'],
            ['63910', 'News agency activities'],
            ['63990', 'Other information service activities'],
            ['64110', 'Monetary central bank'],
            ['64120', 'Other monetary intermediation'],
            ['64200', 'Holding companies'],
            ['64301', 'Trusts, funds and similar financial entities'],
            ['64302', 'Pension funding'],
            ['64910', 'Financial leasing'],
            ['64920', 'Other credit granting'],
            ['64991', 'Security and commodity contracts brokerage'],
            ['64999', 'Other financial service activities'],
            ['65110', 'Insurance'],
            ['65120', 'Reinsurance'],
            ['65201', 'Life insurance'],
            ['65202', 'Pension funding'],
            ['65300', 'Insurance and pension funding'],
            ['66110', 'Administration of financial markets'],
            ['66120', 'Security and commodity exchanges'],
            ['66190', 'Other auxiliary activities'],
            ['66210', 'Risk and damage evaluation'],
            ['66220', 'Activities of insurance agents and brokers'],
            ['66300', 'Fund management activities'],
            ['69101', 'Legal activities'],
            ['69102', 'Accounting and auditing activities'],
            ['69103', 'Tax consulting'],
            ['69201', 'Architectural activities'],
            ['69202', 'Engineering design'],
            ['69203', 'Testing and analysis'],
            ['70100', 'Activities of head offices'],
            ['70200', 'Management consultancy activities'],
            ['71101', 'Renting and leasing of land'],
            ['71102', 'Renting and leasing of buildings'],
            ['71201', 'Renting and leasing of land'],
            ['71202', 'Renting and leasing of buildings'],
            ['72100', 'Research and experimental development on natural sciences and engineering'],
            ['72200', 'Research and experimental development on social sciences and humanities'],
            ['73101', 'Advertising agencies'],
            ['73102', 'Media representation'],
            ['73200', 'Market research and public opinion polling'],
            ['74100', 'Specialized design activities'],
            ['74201', 'Photographic activities'],
            ['74202', 'Translation and interpretation activities'],
            ['74901', 'Environmental consulting'],
            ['74902', 'Other professional activities'],
            ['77101', 'Renting and leasing of automobiles'],
            ['77102', 'Renting and leasing of trucks'],
            ['77210', 'Renting and leasing of recreational and sports goods'],
            ['77220', 'Renting and leasing of video tapes and disks'],
            ['77290', 'Renting and leasing of other consumer goods'],
            ['77300', 'Renting and leasing of other machinery and equipment'],
            ['77401', 'Licensing of intellectual property'],
            ['77402', 'Franchising'],
            ['81101', 'Combined facilities support activities'],
            ['81102', 'Office administrative activities'],
            ['81210', 'Cleaning activities'],
            ['81220', 'Specialized cleaning activities'],
            ['81291', 'Photocopying and document preparation'],
            ['81292', 'Secretarial and translation services'],
            ['82110', 'General secondary education'],
            ['82120', 'Technical and vocational secondary education'],
            ['82201', 'Primary education'],
            ['82202', 'Pre-primary education'],
            ['82301', 'Post-secondary non-tertiary education'],
            ['82302', 'Tertiary education'],
            ['82410', 'Sports and recreation education'],
            ['82420', 'Cultural education'],
            ['82910', 'Driving schools'],
            ['82920', 'Other education'],
            ['84110', 'General public administration activities'],
            ['84120', 'Regulation of health care, education, cultural services'],
            ['84130', 'Regulation of economic activities'],
            ['84210', 'Foreign affairs'],
            ['84220', 'Defence activities'],
            ['84230', 'Public order and safety activities'],
            ['84300', 'Compulsory social security activities'],
            ['85101', 'Hospital activities'],
            ['85102', 'Medical and dental practice activities'],
            ['85201', 'General medical practice activities'],
            ['85202', 'Specialist medical practice activities'],
            ['85301', 'Residential care activities'],
            ['85320', 'Social work activities without accommodation'],
            ['85510', 'Pre-primary education'],
            ['85520', 'Primary education'],
            ['85530', 'Secondary education'],
            ['85590', 'Other education'],
            ['86101', 'Hospital activities'],
            ['86102', 'Medical and dental practice activities'],
            ['86210', 'General medical practice activities'],
            ['86220', 'Specialist medical practice activities'],
            ['86901', 'Human health activities'],
            ['86909', 'Other human health activities'],
            ['87101', 'Residential nursing care activities'],
            ['87102', 'Residential care activities for mental retardation'],
            ['87109', 'Other residential care activities'],
            ['87201', 'Social work activities without accommodation for the elderly and disabled'],
            ['87209', 'Other social work activities without accommodation'],
            ['88101', 'Social work activities without accommodation for the elderly and disabled'],
            ['88102', 'Child day-care activities'],
            ['90101', 'Performing arts'],
            ['90102', 'Support activities to performing arts'],
            ['90201', 'Museum activities'],
            ['90202', 'Historical sites and buildings'],
            ['90301', 'Operation of arts facilities'],
            ['90302', 'Operation of historical sites and buildings'],
            ['91010', 'Library and archives activities'],
            ['91020', 'Museums activities'],
            ['91030', 'Operation of historical sites and buildings'],
            ['91041', 'Botanical and zoological gardens'],
            ['91042', 'Nature reserves'],
            ['93110', 'Operation of sports facilities'],
            ['93120', 'Other sports activities'],
            ['93191', 'Operation of sports facilities'],
            ['93192', 'Other sports activities'],
            ['93210', 'Amusement parks and theme parks'],
            ['93290', 'Other amusement and recreation activities'],
            ['94110', 'Motion picture and video production'],
            ['94120', 'Motion picture and video distribution'],
            ['94130', 'Motion picture projection'],
            ['95110', 'Repair of computers and communication equipment'],
            ['95120', 'Repair of household appliances'],
            ['95210', 'Repair of footwear and leather goods'],
            ['95220', 'Repair of furniture and home furnishings'],
            ['95230', 'Repair of bicycles'],
            ['95290', 'Repair of other goods'],
            ['96010', 'Laundry and dry cleaning'],
            ['96020', 'Hairdressing and beauty treatment'],
            ['96030', 'Funeral and related activities'],
            ['97010', 'Activities of households as employers'],
            ['97020', 'Undifferentiated goods-producing activities of private households'],
            ['99000', 'Activities of extraterritorial organizations and bodies'],
        ];

        foreach ($msicCodes as $msic) {
            Setting::firstOrCreate(
                [
                    'category' => 'MSIC',
                    'name' => $msic[0],
                ],
                [
                    'value' => $msic[1],
                    'description' => $msic[1],
                    'is_active' => true,
                ]
            );
        }

        // Product Classifications (CLASS)
        $classifications = [
            ['A', 'Animals and live products'],
            ['B', 'Animal products'],
            ['C', 'Vegetable products'],
            ['D', 'Animal or vegetable fats and oils'],
            ['E', 'Foodstuffs'],
            ['F', 'Beverages'],
            ['G', 'Chemicals'],
            ['H', 'Plastics and rubber'],
            ['I', 'Wood and wood products'],
            ['J', 'Pulp and paper'],
            ['K', 'Textiles'],
            ['L', 'Footwear'],
            ['M', 'Stone and glass'],
            ['N', 'Metals'],
            ['O', 'Machinery'],
            ['P', 'Transport equipment'],
            ['Q', 'Precision instruments'],
            ['R', 'Arms and ammunition'],
            ['S', 'Miscellaneous'],
            ['T', 'Works of art'],
        ];

        foreach ($classifications as $classification) {
            Setting::firstOrCreate(
                [
                    'category' => 'Classification',
                    'name' => $classification[0],
                ],
                [
                    'value' => $classification[1],
                    'description' => $classification[1],
                    'is_active' => true,
                ]
            );
        }

        // Measurement Units (UN/ECE Rec. 20)
        $measurements = [
            ['C62', 'Piece'],
            ['CMT', 'Centimeter'],
            ['MTR', 'Meter'],
            ['KGM', 'Kilogram'],
            ['MGM', 'Milligram'],
            ['TON', 'Metric ton'],
            ['LTN', 'Liter'],
            ['MLT', 'Milliliter'],
            ['H87', 'Item'],
            ['HUR', 'Hour'],
            ['DAY', 'Day'],
            ['MON', 'Month'],
            ['YEA', 'Year'],
            ['WEE', 'Week'],
            ['MIN', 'Minute'],
            ['SEC', 'Second'],
            ['SA', 'Square meter'],
            ['S4', 'Square centimeter'],
            ['S7', 'Square kilometer'],
            ['A53', 'Hectare'],
            ['A96', 'Acre'],
            ['LO', 'Cubic meter'],
            ['L83', 'Cubic centimeter'],
            ['MTQ', 'Cubic meter'],
            ['MLT', 'Milliliter'],
        ];

        foreach ($measurements as $measurement) {
            Setting::firstOrCreate(
                [
                    'category' => 'Measurement',
                    'name' => $measurement[0],
                ],
                [
                    'value' => $measurement[1],
                    'description' => $measurement[1],
                    'is_active' => true,
                ]
            );
        }
    }
}
